# Generated by Django 5.1.1 on 2024-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='bd',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
